# Site settings
title: travel blog
email: funtravel@gmail.com
description: My simple blog.
baseurl: "/my-theme"

twitter_username:vips 
avatar: "http://placeimg.com/300/300/people" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Vipin Mohan" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
